apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-redis
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: order-redis
    app.kubernetes.io/instance: order-redis
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: order-redis
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-redis
        app.kubernetes.io/instance: order-redis
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: redis
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
      - name: order-redis
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
          - name: REDIS_PASSWORD
            value: password
        command: ["redis-server"]
        args: ["--requirepass $(REDIS_PASSWORD)"]
---
apiVersion: v1
kind: Service
metadata:
  name: order-redis
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: order-redis
    app.kubernetes.io/instance: order-redis
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    app.kubernetes.io/instance: order-redis
    app.kubernetes.io/component: redis
  ports:
  - name: order-redis-port
    port: 6379
    targetPort: 6379
