apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-pubsub
  namespace: nautible-app
  labels:
    app.kubernetes.io/name: order-pubsub
    app.kubernetes.io/instance: order-pubsub
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pubsub
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: order-redis:6379
  - name: redisPassword
    value: password
