---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-order
        image: public.ecr.aws/nautible/nautible-app-ms-order:bd0a0f6d117fb01732973318da9edbf15f803ffe
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
