---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-order
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-order
        image: public.ecr.aws/nautible/nautible-app-order:62acfcb06359b5b4f09323871c7ad92331b84fc2
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
