---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-order
        image: public.ecr.aws/nautible/nautible-app-ms-order:7f084a9614b4d482b3e60536f44c3b2125039459
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
