---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-order
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-order
        image: public.ecr.aws/nautible/nautible-app-order:a78505647d034b4c651368102c9facea05d4c988
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
