---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-order
        image: public.ecr.aws/nautible/nautible-app-ms-order:080f8ee6a7005f49c4235b3cf6872cbbe4ec3a0b
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
