---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-order
  namespace: nautible-app
  labels:
    app.kubernetes.io/name: nautible-app-order
    app.kubernetes.io/instance: nautible-app-order
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-order
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-order
        app.kubernetes.io/instance: nautible-app-order
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nautible-app-order"
        dapr.io/app-port: "8080"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' # https://github.com/dapr/dapr/issues/2657
    spec:
      containers:
      - name: nautible-app-order
        image: public.ecr.aws/nautible/nautible-app-order:dummy
        ports:
          - containerPort: 8080
          - containerPort: 9000
        livenessProbe:
          httpGet:
            port: 8080
            path: /health/live
          failureThreshold: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8080
            path: /health/ready
          failureThreshold: 10
          periodSeconds: 30

