---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-order
        image: nautibledevacr.azurecr.io/nautible-app-ms-order:ae7346f88ae7d7feb3ddf11cb5c7a77f26ceb879
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
