---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-order
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-order
        image: nautibledevacr.azurecr.io/nautible-app-order:62acfcb06359b5b4f09323871c7ad92331b84fc2
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_PW
