---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-order
        image: nautibledevacr.azurecr.io/nautible-app-ms-order:244fd12c75bc8621e5192f23b11f722fe146dde6
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
