apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-pubsub
  namespace: nautible-app
  labels:
    app.kubernetes.io/name: order-pubsub
    app.kubernetes.io/instance: order-pubsub
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pubsub
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: secret-nautible-app-common
      key: SERVICE_BUS_CONNECTION_STRING
